name: PR Discord Notification

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR notification to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"username": "GitHub", "content": "🚀 A new Pull Request has been opened: ${{ github.event.pull_request.html_url }}"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
